[tool.black]
line-length = 79
target-version = ["py38"]
exclude = """
(
  /(
      /.git
    | /.github
    | /.pytest_cache
    | /.venv
  )/
)
"""


[tool.pytest.ini_options]
console_output_style = "count"
filterwarnings = [
    "ignore::DeprecationWarning",
]


[tool.isort]
force_single_line = true
line_length = 79
multi_line_output = 3
profile = "black"


[tool.pylint.'MESSAGES CONTROL']
disable = [
    "C0114",  # Missing module docstring (missing-module-docstring)
    "C0115",  # Missing class docstring (missing-class-docstring)"
    "C0116",  # Missing function or method docstring (missing-function-docstring)"
    "E0611",  # No name 'XXX' in module 'xxx' (no-name-in-module)"
    "R0903",  # Too few public methods (too-few-public-methods)
]
ignore = ["./.venv/"]
max_line_length = 79


[tool.pylint.REPORTS]
output_format = "colorized"


[tool.coverage.run]
branch = true
source = [
    "./src",
]


[tool.coverage.html]
directory = "./tests/coverage_html_report/"


[tool.coverage.report]
#fail_under = 90
sort = "Cover"
